name: dodoshautopark
description: "A new Flutter project."

version: 1.0.4+4

environment:
  sdk: '>=3.4.0-211.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.10.0
  file_picker: ^9.0.2
  flutter_snake: ^1.1.0
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  http: ^1.3.0
  flutter_svg: ^1.0.0
  connectivity_plus: ^5.0.2
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_carousel_widget: ^2.2.0
  amplify_flutter: ^2.6.1
  amplify_storage_s3: ^2.6.1
  image_picker: ^1.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/img/