const Map<String, Map<String, dynamic>> STRINGS = {
  "ru": {
    "brands": "Бренды",
    "toggle_button": ["Все", "Новые", "С пробегом"],
    "brand": "Марка",
    "autoBrand": "Марка автомобиля",
    "find": "Найти",
    "search_results": "Результаты поиска",
    "catalog": "Каталог",
    "publish": "Опубликовать",
    "marked": "Избранное",
    "my_ads": "Мои объявления",
    "home": "Главная",
    "settings": "Настройки",
    "language": "Язык",
    "logout": "Выйти",
    "profile": "Профиль",
    "notifications": "Уведомления",
    "help": "Помощь",
    "about": "О нас",
    "add_announcement_question": "Хотите добавить объявление?",
    "add_announcement_description": "Перед тем как ваше авто станет доступно тысячам покупателей, проверьте все данные. Убедитесь, что фото, описание и цена соответствуют вашим ожиданиям. Когда будете готовы – нажмите «Начать публикацию» и ваше объявление появится в «Авто Парк»!",
    "add_announcement_button": "Начать публикацию",
    "back": "Назад",
    "next": "Вперед",
    "price": "Цена",
    "description": "Описание",
    "region": "Регион",
    "photo": "Фото",
    "details": "Детали",
    "car": "Автомобиль",
    "special_equipment": "Спецтехника",
    "bus": "Автобус",
    "other": "Другое",
    "motorcycle": "Мотоцикл", 
    "vehicle_details": "Детали автомобиля",
    "model": "Модель",
    "year": "Год",
    "color": "Цвет",
    "engine_capacity": "Объем двигателя",
    "fuel_type": "Тип топлива",
    "transmission": "КПП",
    "add_photos": "Добавить фото",
    "add_photos_description": "Добавьте фотографии вашего автомобиля, чтобы привлечь больше внимания и увеличить шансы на продажу.",
    "add_photos_button": "Добавить фото",
    "photos_selected": "фото выбрано",
    "error_picking_images": "Ошибка при выборе фото",
    "choose_again": "Выбрать заново",
    "choose_photo_error" : "Выберите хотя бы 1 фото",
    "price_in_dollars" : "Цена в \$",
    "select_region": "Выберите регион, где находится ваш автомобиль",
    "fill_details": "Заполните детали вашего автомобиля",
    "brand_model_required": "Пожалуйста, выберите марку и модель",
    "year_required": "Пожалуйста, выберите год",
    "price_required": "Пожалуйста, введите цену",
    "region_required": "Пожалуйста, выберите регион",
    "images": "Фотографии",
    "success": "Успешно",
    "ad_published": "Ваше объявление успешно опубликовано",
    "close": "Закрыть",
    "error": "Ошибка",
    "error_message": "Пожалуйста, проверьте ваши данные и попробуйте снова",
    "error_title": "Ошибка",
    "error_description": "Пожалуйста, проверьте ваши данные и попробуйте снова",
    "error_button": "Попробовать снова",
    "error_button_text": "Попробовать снова",
    "back_to_main": "Вернуться на главную",
    "uploading": "Загрузка...",
    "marked_ads": "Сохраненные объявления",
    "recently_viewed": "Недавно просмотренные",
    "my_favorites": "Самые популярные",
    "preferences": "Настройки",
    "currency": "Валюта",
    "phone": "Телефон",
    "email": "Email",
    "name": "Имя",
    "password": "Пароль",
    "profile_image": "Фото профиля",
    "update_profile_image": "Обновить фото профиля",
    "personal_info": "Личные данные",
  },
  "ky": {
    // Add Kyrgyz translations here
  },
};

const String LANG = "ru";
